substitutions:
  device_name: didiessefrog
  #board: d1_mini
  board: esp01_1m
  platform: ESP8266
  esp8266_store_log_strings_in_flash: 'false'
  
esphome:
  name: $device_name
  platform: $platform
  board: $board
  board_flash_mode: dout

<<: !include base.txt

button:
  - platform: safe_mode
    name: "Restart (Safe Mode)"

wifi:
  networks:
  - ssid: !secret ssid2
    password: !secret wifi_password1
 # - ssid: !secret ssid1
 #   password: !secret wifi_password2
#  - ssid: !secret ssid3
#    password: !secret wifi_password3
#  - ssid: "wlan"
#    password: "mimmoelisabettaluciaantonio"
#  - ssid: "wlan2"
#    password: "mimmoelisabettalucia"
#  - ssid: "D0m0t1c4"
#    password: "mimmoelisabettalucia"
  ap:
    ssid: "didiessefrog"
    password: ""
#  manual_ip:
#    static_ip: 192.168.1.205
#    gateway: 192.168.1.1
#    subnet: 255.255.255.0
captive_portal:
web_server:
  port: 80
api:



ota:
  - platform: esphome
 #safe_mode: true
logger:
  level: DEBUG
  baud_rate: 0

#external_components:
#  - source: github://pr#3331
#    components: ["json"]
######################
######################
sensor:
  - platform: template
    name: "Serbatoio"
    id: serbatoio
    unit_of_measurement: "%"
    lambda: |-
        if (((id(peso).state)/1)*100 < 0) { return 0; } 
        else if (((id(peso).state)/1)*100 > 100) { return 100; }
        else { return  (((id(peso).state)  / 1 )*100 ); }
    accuracy_decimals: 0
    update_interval: 10s
  - platform: template
    name: "Litri Netti"
    id: netto
    unit_of_measurement: "L"
    lambda: |-
      if (((id(peso).state)*1)> 0)  { return ( ((id(peso).state) * 1) );  }
      else {return 0;}
    accuracy_decimals: 1
    update_interval: 10s    
    
  - platform: hx711
    name: "Peso Totale"
    dout_pin: GPIO1
    clk_pin: GPIO3
    #gain: 128
    update_interval: 5s
    id: peso
    accuracy_decimals: 2
    unit_of_measurement: Kg
    filters:
      - calibrate_linear:
          - -129027 -> 0.0
          - 234506 -> 0.943
          - 383268 -> 1.3290
          #- 267130 -> 1
         # - 393000 -> 1

#  - platform: max6675
#    name: "Temperatura Caldaia Caffè"
#    cs_pin: GPIO14
#    update_interval: 10s
binary_sensor:
  - platform: gpio
    internal: true
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "pulsante $device_name"
    on_click:
    - min_length: 50ms
      max_length: 350ms
      then:
        - switch.toggle: relay
 # - platform: status
#    name: "stato $device_name"
switch:
  - platform: gpio
    name: $device_name
    pin: GPIO12
    id: relay
 # - platform: gpio
  #  name: led
  #  pin: GPIO13
  #  id: led
  - platform: restart
    name: "riavvia $device_name"
light:
  - platform: status_led
    pin: GPIO13
    name: led 
    internal: True
    

#status_led:
 # pin:
  #  number: GPIO13
   # inverted: true

#spi:
#  miso_pin: GPIO01
#  clk_pin: GPIO03

